export const HOME_ROUTE = '/'
export const PRODUCT_ROUTE = '/product'
export const LOVES_ROUTE = '/loves'
export const CATALOG_ROUTE = '/catalog'
export const COMPARE_ROUTE = '/compare'
export const BASKET_ROUTE = '/basket'
export const USER_ROUTE = '/user'
export const REGISTRATION_ROUTE = '/registration'
export const NEWS_ROUTE = '/news'
export const ADMIN_ROUTE = '/admin'

